### ISSUE TITLE
Server IPS

### ISSUE THREAD

**Issue by Driesboy** [Driesboy/Genisys-1.0.0#1]
set your minecraft pe server ip down below

**Comment by MateiGamingYTB** [comment]
ILOVEMCPE.ddns.net port 19132 (Default)
Server is in BETA have Whitelist, open at night, but my work at night.....

**Comment by erkam2002** [comment]
Double fall damage Gamination.de Port 19133

**Comment by leonardoFTW** [comment]
173.208.169.138
        19154
